spring:
  application:
    name: ChatBotTest

  cache:
    type: caffeine
    cache-names: weatherCache

bot:
  name-bot: "ChatBot"
  bot-token: ${BOT_TOKEN}

openweather:
  api-key: ${OPENWEATHER_API_KEY}
  base-url: https://api.openweathermap.org/data/2.5

logging:
  level:
    org.springframework.cache: TRACE
    oleborn.chatbottest.weather.cache.CachedWeather: DEBUG